name: Build Docs

on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        TARGET_BRANCH: docs
        BUILD_SCRIPT: git config --global --add safe.directory "*" && npm ci && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/
